name: Android CI Code Refactor

on:
  pull_request:
    branches: [ develop ]

jobs:
  refactor:

    runs-on: ubuntu-20.04

    env:
      TERM: dumb

    steps:
      - name: Generate build number
        shell: bash
        run: |
          echo "name=BUILD_NUMBER::$(expr $GITHUB_RUN_NUMBER + 5200)" >> GITHUB_ENV
      - uses: actions/checkout@v2
        with:
          ref: ${{ github.event.pull_request.head.sha }}

      - name: Set up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: 11

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Head branch name
        shell: bash
        run: echo "##[set-output name=branch;]$(echo ${HEAD_BRANCH})"
        env:
          HEAD_BRANCH: ${{ github.head_ref }}
        id: head_branch_name

      - name: Create new github branch
        uses: peterjgrainger/action-create-branch@v2.2.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          branch: ${{ steps.head_branch_name.outputs.branch }}-refactored

      - name: Fetch and checkout new branch from base branch
        run: |
          git fetch origin ${{ steps.head_branch_name.outputs.branch }}:${{ steps.head_branch_name.outputs.branch }}-refactored
          git checkout ${{ steps.head_branch_name.outputs.branch }}-refactored
      - name: Reformat Code
        run: ./gradlew spotlessApply
        id: reformat

      - name: Checkout base branch
        run: git checkout ${{ steps.head_branch_name.outputs.branch }}
        if: steps.reformat.outputs.exit_code == 0

      - name: Create Pull Request
        id: cpr
        uses: peter-evans/create-pull-request@v3
        with:
          committer: github-actions[bot] <github-actions[bot]@users.noreply.github.com>
          author: github-actions[bot] <github-actions[bot]@users.noreply.github.com>
          branch: ${{ steps.head_branch_name.outputs.branch }}-refactored
          labels: refactor
          assignees: <github-actions[bot]@users.noreply.github.com>
          reviewers: |
            akshay253101
            kameshyadavky
          commit-message: Spotless Applied, Code Reformatted
          title: Spotless applied on ${{ steps.head_branch_name.outputs.branch }}
          body: This is an auto refactored code.
          delete-branch: true

      - name: Branch cleanup
        if: steps.reformat.outputs.exit_code != 0
        run: git push -d origin ${{ steps.head_branch_name.outputs.branch }}-refactored
